name: fastapi
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.17
  - pip=25.1
  - python=3.10.18
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - build==1.3.0
      - certifi==2025.8.3
      - click==8.2.1
      - colorama==0.4.6
      - dnspython==2.7.0
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.8
      - git-filter-repo==2.47.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mysql-connector-python==9.0.0
      - orjson==3.11.2
      - packaging==25.0
      - pip-tools==7.5.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyproject-hooks==1.2.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - rich==14.1.0
      - rich-toolkit==0.15.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.32
      - starlette==0.37.2
      - tomli==2.3.0
      - typer==0.16.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - ujson==5.11.0
      - uvicorn==0.35.0
      - watchfiles==1.1.0
      - websockets==15.0.1
prefix: C:\Users\tyj45\anaconda3\envs\fastapi
